version: '3.5'

networks:
  dss-network:

services:
  dss:
    image: dataiku/dss
    container_name: ${COMPOSE_PROJECT_NAME}_dss
    volumes:
      - /data/dss:/home/dataiku/dss
      - ./requirements.txt:/home/dataiku/requirements.txt
    environment:
      - mem_limit=${DSS_MEM}
    ports:
      - ${PORT}:10000
    networks:
      - dss-network

  postgres:
    depends_on: 
      - dss
    image: postgres:9.6.5-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - dss-network
